#!/usr/bin/env python3
"""
generate_variance.py

Generates a filled Variance / Risk-Acceptance Record (per
execution-plan/templates/VARIANCE-RISK-ACCEPTANCE-TEMPLATE.md) for ONE
STIG finding, identified by its official DISA Vulnerability ID
(e.g. "V-253259"), using the offline reference database built by
stig_reference_builder.py.

This intentionally does NOT parse live Nessus/.SCC/OSCAP scan-result
files. The offline reference database (built by bulk-importing official
DISA XCCDF/.zip documents) supplies the official finding metadata; the
human preparer supplies the asset-specific, scan-specific facts by hand
in Sections 2 and 6 of the generated document. This keeps the tool
simple, reliable, and independent of any particular scan tool's export
format -- if you later want to pre-fill Section 6 from an actual scan
export, treat that as a separate, optional enhancement layered on top of
this generator, not a prerequisite for it.

USAGE
-----
  python3 generate_variance.py \\
      --id V-253259 \\
      --asset WIN11-WKSTN-042 \\
      --system-scope "Example Enclave A" \\
      --detection-method "Manual STIG checklist review" \\
      --detection-date 2026-07-17 \\
      --preparer "J. Smith, ISSO" \\
      [--reference-db execution-plan/tools/data/stig_reference.json] \\
      [--output-dir execution-plan/variance-records]

If --asset/--system-scope/etc. are omitted, the generated document keeps
the corresponding fields blank for the preparer to fill in by hand --
this script never fabricates asset-specific facts.
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timedelta, timezone

DEFAULT_DB = os.path.join(os.path.dirname(__file__), "data", "stig_reference.json")
DEFAULT_OUTPUT_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "variance-records")
)

SLA_DAYS_BY_CAT = {"CAT I": 30, "CAT II": 90, "CAT III": 180}

RACI_BY_CAT = {
    "CAT I": {
        "responsible": "ISSO or Privileged User who identified the finding",
        "accountable": "AO / DAO",
        "consulted": "ISSM, Information Owner/Steward",
        "informed": "Risk Executive Function, CISO",
    },
    "CAT II": {
        "responsible": "ISSO or Privileged User who identified the finding",
        "accountable": "ISSM",
        "consulted": "Information Owner/Steward",
        "informed": "AO/DAO (Informed only)",
    },
    "CAT III": {
        "responsible": "ISSO or Privileged User who identified the finding",
        "accountable": "ISSO",
        "consulted": "ISSM",
        "informed": "\u2014",
    },
}


def load_db(db_path):
    if not os.path.exists(db_path):
        print(f"No reference database found at {db_path}.")
        print("Run: python3 stig_reference_builder.py build")
        sys.exit(1)
    with open(db_path, encoding="utf-8") as f:
        return json.load(f)


def blank(value):
    return value if value else "*(fill in)*"


def render_variance_record(finding, args):
    vuln_id = finding["vuln_id"]
    cat = finding.get("cat", "UNKNOWN")
    raci = RACI_BY_CAT.get(cat, RACI_BY_CAT["CAT III"])
    sla_days = SLA_DAYS_BY_CAT.get(cat, 180)

    detection_date_str = args.detection_date or datetime.now().strftime("%Y-%m-%d")
    try:
        detection_date = datetime.strptime(detection_date_str, "%Y-%m-%d")
    except ValueError:
        detection_date = datetime.now()
    due_date = (detection_date + timedelta(days=sla_days)).strftime("%Y-%m-%d")

    asset_safe = re.sub(r"[^A-Za-z0-9_-]", "_", args.asset) if args.asset else "UNSPECIFIED-ASSET"
    record_id = f"VAR-{vuln_id}-{asset_safe}-{detection_date.strftime('%Y%m%d')}"

    cci_refs = ", ".join(finding.get("cci_refs", [])) or "*(none listed in benchmark)*"

    doc = f"""# Variance / Risk-Acceptance Record — {record_id}

> Generated by `execution-plan/tools/generate_variance.py` from the offline STIG reference database on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. Official finding text (Sections 1 and 8) is sourced verbatim from DISA-published content ({finding.get('source_file', 'unknown source file')}) — do not hand-edit those fields; refresh the reference database from a current official STIG package instead. Sections 2, 3, 6, 7, 9, and 10 require human input and are intentionally left as fill-in prompts below.
>
> Structure per `execution-plan/templates/VARIANCE-RISK-ACCEPTANCE-TEMPLATE.md`.

## 1. Identity

| Field | Value |
|---|---|
| Variance Record ID | {record_id} |
| STIG Vulnerability ID | {vuln_id} |
| STIG Rule ID | {finding.get('rule_id', '')} |
| STIG Rule Version (short ID) | {finding.get('stig_id', '')} |
| Benchmark / STIG Title | {finding.get('benchmark_title', '')} |
| Benchmark Release | {finding.get('release', '')} |
| Finding Title | {finding.get('title', '')} |
| Severity / CAT Level | {cat} (raw severity: {finding.get('severity', '')}) |
| CCI Reference(s) | {cci_refs} |
| System / Enclave Scope | {blank(args.system_scope)} |
| Document Version | v1.0 |
| Last Reviewed | {blank(args.detection_date)} |

## 2. Trigger and Cadence

| Field | Value |
|---|---|
| Trigger Condition | Configuration/vulnerability review identified this finding as **Open** *(preparer: confirm or correct)* |
| Detection Date | {detection_date_str} |
| Detection Method | {blank(args.detection_method)} |
| Reporting Period | *(fill in)* |
| Re-Review / Decision Due Date | **{due_date}** ({sla_days}-day SLA for {cat}, per `execution-plan/templates/ESCALATION-MATRIX.md`) |
| Repository Location | `execution-plan/variance-records/{record_id}.md` |

## 3. Preconditions

| Field | Value |
|---|---|
| Required Access | Read access to the affected asset's configuration baseline; read access to the offline STIG reference database |
| Required Tools | Offline STIG reference database; local ticketing/GRC system record for cross-linking |
| Preparer | {blank(args.preparer)} |
| Input Artifacts | Official DISA STIG check/fix text below; prior variance record for this finding/asset pair, if this is a renewal |

## 4. RACI (Severity-Tiered — {cat})

| Role | Assignment |
|---|---|
| Responsible (prepares record) | {raci['responsible']} |
| **Accountable (final accept/reject authority)** | **{raci['accountable']}** |
| Consulted | {raci['consulted']} |
| Informed | {raci['informed']} |
| Evidence Owner | ISSO |
| Escalation Owner | ISSM |

## 5. Execution Steps (Preparation)

1. Confirm the Vulnerability ID and affected asset(s) above are correct.
2. Fill in Section 2's Detection Method and Reporting Period.
3. Complete Section 6 (Validation) with the actual observed state of the asset — first-person, factual, not a restatement of the check text below.
4. Route the draft to the Consulted role(s) in Section 4 for comments before requesting sign-off.
5. Route to the Accountable role in Section 4 for the risk decision. Do not proceed to Closure (Section 10) until that signature is captured.

## 6. Validation

| Field | Value |
|---|---|
| Assessment Method | *(Examine / Interview / Test — state which was used)* |
| Expected Result (per official check text) | See official check text in Section 8 |
| Actual Result Observed | *(fill in — what was actually found on the asset)* |
| Pass / Fail | *(Pass = Not a Finding; Fail = Open)* |
| Reviewed By | *(fill in)* |
| Review Date | *(fill in)* |

## 7. Evidence Package

| Field | Value |
|---|---|
| Artifact List | *(fill in)* |
| Repository Path | `execution-plan/variance-records/evidence/{record_id}/` |
| Retention Period | Per local records-retention policy (minimum: current + 1 prior accreditation cycle) |
| Chain-of-Custody Note | *(fill in)* |

## 8. Findings and Exceptions (Official Reference — Auto-Populated)

| Field | Value |
|---|---|
| Official Finding Description | {finding.get('description', '')} |

**Official Check Text:**

{finding.get('check_text', '*(none in benchmark)*')}

**Official Fix Text:**

{finding.get('fix_text', '*(none in benchmark)*')}

| Field | Value |
|---|---|
| Affected Asset(s) | {blank(args.asset)} |
| Exception Type | ☐ Risk Acceptance &nbsp;&nbsp; ☐ Compensating Control &nbsp;&nbsp; ☐ False Positive Correction &nbsp;&nbsp; ☐ Remediation In Progress |
| Rationale | *(fill in)* |
| Compensating Controls | *(fill in, if any)* |
| POA&M ID | *(fill in, if applicable)* |

## 9. Remediation and Escalation

| Field | Value |
|---|---|
| Decision | ☐ Accept Risk &nbsp;&nbsp; ☐ Reject — Remediate &nbsp;&nbsp; ☐ Mitigate with Compensating Control |
| Remediation Plan (if not accepting as-is) | *(fill in)* |
| Owner | *(fill in)* |
| Scheduled Completion Date | *(fill in — must not exceed {due_date} unless a separately approved POA&M milestone applies)* |
| Escalation Trigger | Automatic if {due_date} is missed — see `execution-plan/templates/ESCALATION-MATRIX.md` |
| Escalation Owner | ISSM |

## 10. Closure and Sign-Off

| Role | Name | Signature | Date | Decision Recorded |
|---|---|---|---|---|
| Preparer | {blank(args.preparer)} | | | |
| ISSM (standing reviewer, all tiers) | | | | |
| **{raci['accountable']}** (Accountable per Section 4) | | | | |

| Field | Value |
|---|---|
| Next Due Date (re-review) | {due_date}, or sooner if the Decision above requires earlier follow-up |
| Lessons Learned / Runbook Update Flag | *(fill in)* |

---
*Official content sourced from: {finding.get('source_file', 'unknown')} (imported from https://public.cyber.mil/stigs/downloads/ into the offline reference database).*
"""
    return record_id, doc


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--id", required=True, help="STIG Vulnerability ID, e.g. V-253259")
    parser.add_argument("--asset", default="", help="Affected asset/hostname identifier")
    parser.add_argument("--system-scope", default="", dest="system_scope", help="System/enclave name")
    parser.add_argument("--detection-method", default="", dest="detection_method")
    parser.add_argument("--detection-date", default="", dest="detection_date", help="YYYY-MM-DD")
    parser.add_argument("--preparer", default="", help="Name and role of the preparer")
    parser.add_argument("--reference-db", default=DEFAULT_DB, dest="reference_db")
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR, dest="output_dir")
    args = parser.parse_args()

    db = load_db(args.reference_db)
    finding = db.get("findings", {}).get(args.id)
    if not finding:
        print(f"'{args.id}' not found in the offline reference database "
              f"({db.get('finding_count', 0)} findings loaded from "
              f"{len(db.get('source_files', []))} official STIG file(s)).")
        print("Import the relevant official STIG .zip/xccdf into execution-plan/tools/stig_intake/ "
              "and re-run stig_reference_builder.py build.")
        sys.exit(1)

    record_id, doc = render_variance_record(finding, args)

    os.makedirs(args.output_dir, exist_ok=True)
    out_path = os.path.join(args.output_dir, f"{record_id}.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(doc)

    print(f"Generated: {out_path}")
    print(f"  Finding:  {finding['title']}")
    print(f"  Severity: {finding['cat']}")
    print(f"  Accountable role for final decision: {RACI_BY_CAT.get(finding['cat'], RACI_BY_CAT['CAT III'])['accountable']}")


if __name__ == "__main__":
    main()
